### ISSUE TITLE
`path_type` and `query_type` macros are unnecessary

### ISSUE THREAD

**Issue by AzureMarker** [petar-dambovaliev/darpi#1]
The [`path_type`] and [`query_type`] macros generate pretty much the same code for every input.

`path_type` builds in a slightly custom deserialization function to each struct property (wrapping the deserialization error in a custom struct), but I expect that that could be implemented outside of the macro (i.e. in the library code when it tries to deserialize the struct.

`query_type` doesn't modify the struct and the trait impl it creates is the same every time (it doesn't need to be created special for each struct).

In case one of these macros is still necessary, I would recommend using a derive macro instead of a full attribute macro.

[`path_type`]: https://github.com/petar-dambovaliev/darpi/blob/aff7d81631fabe740f165a2e16dfe918a43c878b/darpi-code-gen/src/lib.rs#L21
[`query_type`]: https://github.com/petar-dambovaliev/darpi/blob/aff7d81631fabe740f165a2e16dfe918a43c878b/darpi-code-gen/src/lib.rs#L71

**Comment by petar-dambovaliev** [comment]
Thank you for the feedback.
Yes, you are totally right.
The code generation crate is a mess right now.
Cleaning up is next on my list.

**Comment by petar-dambovaliev** [comment]
done
