### ISSUE TITLE
Unable to customize shaku module

### ISSUE THREAD

**Issue by AzureMarker** [petar-dambovaliev/darpi#2]
The shaku module is passed in as a type reference. This prevents users from customizing it (passing parameters or overriding services).

**Comment by petar-dambovaliev** [comment]
The module argument is defined as `Arc<T>` .The end result of the handler arguments for lets say `Logger` and `UserService` would be 

`T: shaku::HasComponent<dyn Logger + 'static>
            + shaku::HasComponent<dyn UserService + 'static>,`
            
My experience with `shaku` is very limited. Can you please, give a concrete example?

**Comment by AzureMarker** [comment]
I'm referring to the `run` macro used in `main`:
```rust
#[tokio::main]
async fn main() {
    // the `run` macro creates and runs the server
    run!({
        // the provided address is verified at compile time
        address: "127.0.0.1:3000",
        // via the container we inject our dependencies
        // in this case, MyLogger type
        // any handler that has the trait Logger as an argument
        // will be given MyLogger
        module: Container,
        bind: [
            // ...
        ],
    });
}
```

The `module` argument looks like it's just a type reference to a module type (created with the shaku `module` macro). The module could be customized at runtime, but this API doesn't support that. Example of customizing a shaku module (taken from the [shaku readme](https://github.com/Mcat12/shaku/blob/master/README.md)):
```rust
let module = MyModule::builder()
    .with_component_parameters::<DateLoggerImpl>(DateLoggerImplParameters {
        today: "Jan 26".to_string(),
        year: 2020
    })
    .build();
```

**Comment by petar-dambovaliev** [comment]
> I'm referring to the `run` macro used in `main`:
> ```rust
> #[tokio::main]
> async fn main() {
>     // the `run` macro creates and runs the server
>     run!({
>         // the provided address is verified at compile time
>         address: "127.0.0.1:3000",
>         // via the container we inject our dependencies
>         // in this case, MyLogger type
>         // any handler that has the trait Logger as an argument
>         // will be given MyLogger
>         module: Container,
>         bind: [
>             // ...
>         ],
>     });
> }
> ```
> 
> The `module` argument looks like it's just a type reference to a module type (created with the shaku `module` macro). The module could be customized at runtime, but this API doesn't support that. Example of customizing a shaku module (taken from the [shaku readme](https://github.com/Mcat12/shaku/blob/master/README.md)):
> ```rust
> let module = MyModule::builder()
>     .with_component_parameters::<DateLoggerImpl>(DateLoggerImplParameters {
>         today: "Jan 26".to_string(),
>         year: 2020
>     })
>     .build();
> ```

Good point. I might introduce a `shaku` component loader that could be implemented on the user side but provide a macro for it as well. Thanks for the feedback.

**Comment by petar-dambovaliev** [comment]
@Mcat12 I have added support for customisation.

```
fn make_container() -> Container {
    let module = Container::builder()
        .with_component_parameters::<DateLoggerImpl>(DateLoggerImplParameters {
            today: "Jan 26".to_string(),
            year: 2020,
        })
        .build();
    module
}

module: make_container => Container,
```
